const options = [
    "Array",
    "String",
    "Hash Table",
    "Dynamic Programming",
    "Math",
    "Sorting",
    "Depth-First Search",
    "Breadth-First Search",
    "Greedy",
    "Database",
    "Tree",
    "Binary Search",
    "Matrix",
    "Binary Tree",
    "Two Pointers",
    "Bit Manipulation",
    "Stack",
    "Design",
    "Heap (Priority Queue",
    "Graph",
    "Simulation",
    "Backtracking",
    "Prefix Sum",
    "Sliding Window",
    "Trie",
    "Linked List"
];